// Generated by splitting main.tsx into per-view components.
// This file composes the Settings view by delegating each section to a
// dedicated panel component. State/handlers/helpers are all typed as `any`
// so that missing-prop checks don't break the build while the rest of the
// refactor is in flight. The root element is the single
// <section className="settings-grid ..."> wrapper plus the inner <aside>.

import type { ReactElement } from 'react';
import { ModelPanel } from './settings/ModelPanel';
import { MarketPanel } from './settings/MarketPanel';
import { DataVendorsPanel } from './settings/DataVendorsPanel';
import { MarketDataVendorsPanel } from './settings/MarketDataVendorsPanel';
import { RoutesPanel } from './settings/RoutesPanel';
import { BacktestPanel } from './settings/BacktestPanel';
import { BillingPanel } from './settings/BillingPanel';
import { UsersPanel } from './settings/UsersPanel';

export interface SettingsViewProps {
  state: any;
  handlers: any;
  helpers: any;
}

export function SettingsView({ state, handlers, helpers }: SettingsViewProps): ReactElement {
  const Panel = helpers.Panel;
  const Lightbulb = helpers.Lightbulb;
  const CircleAlert = helpers.CircleAlert;

  const t = state.t;
  const settingsSection = state.settingsSection;
  const settingsTabs = state.settingsTabs;
  const setupRecommendations = state.setupRecommendations;

  const setSettingsSection = handlers.setSettingsSection;

  return (
    <section className={`settings-grid settings-section-${settingsSection}`}>
      <section className="settings-main">
        <nav className="settings-tabs" aria-label={t.settings}>
          {settingsTabs.map((item: any) => (
            <button
              key={item.key}
              className={settingsSection === item.key ? 'active' : ''}
              onClick={() => setSettingsSection(item.key)}
              aria-current={settingsSection === item.key ? 'page' : undefined}
            >
              {item.icon}
              {item.label}
            </button>
          ))}
        </nav>
        {settingsSection === 'model' && (
          <ModelPanel state={state} handlers={handlers} helpers={helpers} />
        )}

        {settingsSection === 'market' && (
          <MarketPanel state={state} handlers={handlers} helpers={helpers} />
        )}

        {settingsSection === 'data' && (
          <>
            <DataVendorsPanel state={state} handlers={handlers} helpers={helpers} />
            <MarketDataVendorsPanel state={state} handlers={handlers} helpers={helpers} />
          </>
        )}

        {settingsSection === 'routes' && (
          <RoutesPanel state={state} handlers={handlers} helpers={helpers} />
        )}

        {settingsSection === 'backtest' && (
          <BacktestPanel state={state} handlers={handlers} helpers={helpers} />
        )}
      </section>

      <aside className="settings-side">
        {settingsSection === 'billing' && (
          <BillingPanel state={state} handlers={handlers} helpers={helpers} />
        )}

        {settingsSection === 'users' && (
          <UsersPanel state={state} handlers={handlers} helpers={helpers} />
        )}

        {settingsSection !== 'billing' && settingsSection !== 'users' && (
          <Panel title={t.setupRecommendations} icon={<Lightbulb size={17} />}>
            <div className="recommendation-list">
              {setupRecommendations.map((item: string) => (
                <div key={item} className="recommendation-row">
                  <CircleAlert size={15} />
                  <span>{item}</span>
                </div>
              ))}
              {setupRecommendations.length === 0 && <span className="empty">{t.recommendationsOk}</span>}
            </div>
          </Panel>
        )}
      </aside>
    </section>
  );
}
