// Generated by splitting main.tsx into per-view components.
// This file contains the Settings view's JSX. State/handlers/helpers are
// all typed as `any` so that missing-prop checks don't break the build while
// the rest of the refactor is in flight. The root element is the single
// <section className="settings-grid ..."> wrapper plus the inner <aside>.

import type { ReactElement } from 'react';

export interface SettingsViewProps {
  state: any;
  handlers: any;
  helpers: any;
}

export function SettingsView({ state, handlers, helpers }: SettingsViewProps): ReactElement {
  const Panel = helpers.Panel;
  const Field = helpers.Field;
  const Selector = helpers.Selector;
  const SaveButton = helpers.SaveButton;
  const Chip = helpers.Chip;
  const formatMoney = helpers.formatMoney;
  const clampNumber = helpers.clampNumber;
  const researchDepthLabel = helpers.researchDepthLabel;
  const modelOptionsFor = helpers.modelOptionsFor;
  const dataVendorOptionLabel = helpers.dataVendorOptionLabel;
  const marketGroupHasOverride = helpers.marketGroupHasOverride;
  const sharedMarketValue = helpers.sharedMarketValue;
  const marketGroupUsesCustomRoute = helpers.marketGroupUsesCustomRoute;
  const marketGroupCustomSettings = helpers.marketGroupCustomSettings;
  const marketDataOverride = helpers.marketDataOverride;
  const routeModelOptions = helpers.routeModelOptions;
  const modelForRole = helpers.modelForRole;
  const routeLabel = helpers.routeLabel;
  const routeDescription = helpers.routeDescription;
  const deepseekThinkingOptions = helpers.deepseekThinkingOptions;
  const Loader2 = helpers.Loader2;
  const Settings2 = helpers.Settings2;
  const Brain = helpers.Brain;
  const Bot = helpers.Bot;
  const RefreshCw = helpers.RefreshCw;
  const Languages = helpers.Languages;
  const BarChart3 = helpers.BarChart3;
  const Database = helpers.Database;
  const ListOrdered = helpers.ListOrdered;
  const KeyRound = helpers.KeyRound;
  const Activity = helpers.Activity;
  const History = helpers.History;
  const CreditCard = helpers.CreditCard;
  const Users = helpers.Users;
  const UserPlus = helpers.UserPlus;
  const Wallet = helpers.Wallet;
  const Lightbulb = helpers.Lightbulb;
  const CircleAlert = helpers.CircleAlert;

  const t = state.t;
  const locale = state.locale;
  const config = state.config;
  const metadata = state.metadata;
  const publicPricing = state.publicPricing;
  const secretStatus = state.secretStatus;
  const secretDraft = state.secretDraft;
  const settingsSection = state.settingsSection;
  const settingsTabs = state.settingsTabs;
  const provider = state.provider;
  const discoveredModels = state.discoveredModels;
  const isFetchingModels = state.isFetchingModels;
  const showDeepSeekThinkingMode = state.showDeepSeekThinkingMode;
  const customLanguage = state.customLanguage;
  const backtestConfig = state.backtestConfig;
  const adminPricing = state.adminPricing;
  const modelPriceDraft = state.modelPriceDraft;
  const newUserDraft = state.newUserDraft;
  const rechargeDraft = state.rechargeDraft;
  const adminUsers = state.adminUsers;
  const setupRecommendations = state.setupRecommendations;
  const dataApiSecretFields = state.dataApiSecretFields;
  const marketDataSections = state.marketDataSections;
  const isSaving = state.isSaving;
  const stockMarketLabels = state.stockMarketLabels;
  const dataVendorLabels = state.dataVendorLabels;
  const customMethodLabels = state.customMethodLabels;

  const setSettingsSection = handlers.setSettingsSection;
  const changeProvider = handlers.changeProvider;
  const updateConfig = handlers.updateConfig;
  const setSecretDraft = handlers.setSecretDraft;
  const fetchModelsForCurrentProvider = handlers.fetchModelsForCurrentProvider;
  const updateMarketProfile = handlers.updateMarketProfile;
  const saveConfig = handlers.saveConfig;
  const saveSecrets = handlers.saveSecrets;
  const updateVendor = handlers.updateVendor;
  const updateToolVendor = handlers.updateToolVendor;
  const updateMarketGroupVendor = handlers.updateMarketGroupVendor;
  const updateMarketGroupCustomBaseUrl = handlers.updateMarketGroupCustomBaseUrl;
  const updateMarketGroupMethodVendor = handlers.updateMarketGroupMethodVendor;
  const updateMarketGroupCustomEndpoint = handlers.updateMarketGroupCustomEndpoint;
  const updateLlmRoute = handlers.updateLlmRoute;
  const updateBacktestConfig = handlers.updateBacktestConfig;
  const saveBacktestSettings = handlers.saveBacktestSettings;
  const updateAdminPricing = handlers.updateAdminPricing;
  const updateDepthPrice = handlers.updateDepthPrice;
  const setModelPriceDraft = handlers.setModelPriceDraft;
  const setNewUserDraft = handlers.setNewUserDraft;
  const createAdminManagedUser = handlers.createAdminManagedUser;
  const setRechargeDraft = handlers.setRechargeDraft;
  const rechargeUser = handlers.rechargeUser;
  const saveAdminPricing = handlers.saveAdminPricing;

  return (
    <section className={`settings-grid settings-section-${settingsSection}`}>
      <section className="settings-main">
        <nav className="settings-tabs" aria-label={t.settings}>
          {settingsTabs.map((item: any) => (
            <button
              key={item.key}
              className={settingsSection === item.key ? 'active' : ''}
              onClick={() => setSettingsSection(item.key)}
              aria-current={settingsSection === item.key ? 'page' : undefined}
            >
              {item.icon}
              {item.label}
            </button>
          ))}
        </nav>
        {settingsSection === 'model' && (
          <Panel title={t.connectionSettings} icon={<Settings2 size={17} />}>
            <div className="form-grid settings-form">
              <Field label={t.provider}>
                <select value={config.llmProvider} onChange={(event) => changeProvider(event.target.value)}>
                  {metadata.providers.map((item: any) => (
                    <option key={item.value} value={item.value}>
                      {item.label}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label={t.providerRegion}>
                <input value={provider?.region ?? '-'} readOnly />
              </Field>
              <label className="field wide">
                <span>{t.baseUrl}</span>
                <input
                  value={config.backendUrl ?? ''}
                  onChange={(event) => updateConfig('backendUrl', event.target.value || null)}
                  placeholder={provider?.defaultBaseUrl ?? t.providerDefault}
                />
              </label>
            </div>

            {provider?.apiKeyField && (
              <label className="secret-row provider-secret">
                <span>
                  {provider.apiKeyField}
                  <small>{secretStatus[provider.apiKeyField]?.configured ? secretStatus[provider.apiKeyField]?.masked : t.notConfigured}</small>
                </span>
                <input
                  type="password"
                  autoComplete="off"
                  placeholder={secretStatus[provider.apiKeyField]?.configured ? t.replaceValue : t.pasteKey}
                  value={secretDraft[provider.apiKeyField] ?? ''}
                  onChange={(event) => setSecretDraft((current: any) => ({ ...current, [provider.apiKeyField!]: event.target.value }))}
                />
              </label>
            )}

            <div className="tool-row settings-model-row">
              <Selector
                icon={<Brain size={16} />}
                label={t.quickModel}
                value={config.quickThinkLlm}
                options={modelOptionsFor('quick', config.quickThinkLlm)}
                onChange={(value: string) => updateConfig('quickThinkLlm', value)}
              />
              <Selector
                icon={<Bot size={16} />}
                label={t.deepModel}
                value={config.deepThinkLlm}
                options={modelOptionsFor('deep', config.deepThinkLlm)}
                onChange={(value: string) => updateConfig('deepThinkLlm', value)}
              />
              <button className="secondary model-fetch-button" onClick={fetchModelsForCurrentProvider} disabled={isFetchingModels || provider?.modelFetch === 'none'}>
                {isFetchingModels ? <Loader2 className="spin" size={16} /> : <RefreshCw size={16} />}
                {isFetchingModels ? t.fetchingModels : t.fetchModels}
              </button>
            </div>
            {provider?.modelFetch === 'none' && <p className="hint">{t.modelFetchUnavailable}</p>}
            {discoveredModels[config.llmProvider]?.length > 0 && (
              <p className="hint">{discoveredModels[config.llmProvider].length} {t.fetchedModels}</p>
            )}
            {showDeepSeekThinkingMode && (
              <div className="settings-thinking-row">
                <Field label={t.deepseekThinkingMode}>
                  <select
                    value={config.deepseekThinkingMode ?? 'disabled'}
                    onChange={(event) => updateConfig('deepseekThinkingMode', event.target.value as any)}
                  >
                    {deepseekThinkingOptions(metadata, locale).map((option: any) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </Field>
                <p className="inline-hint">{t.deepseekThinkingHint}</p>
              </div>
            )}

            <div className="section-title">
              <Languages size={16} />
              {t.outputLanguage}
            </div>
            <div className="chip-grid settings-language-grid">
              {metadata.languages.map((language: any) => (
                <Chip
                  key={language.value}
                  active={config.outputLanguage === language.value}
                  onClick={() => updateConfig('outputLanguage', language.value)}
                >
                  {language.label}
                </Chip>
              ))}
              <input
                className="chip-input"
                placeholder={t.customLanguage}
                value={customLanguage}
                onChange={(event) => updateConfig('outputLanguage', event.target.value)}
              />
            </div>

            <div className="actions-row">
              <SaveButton onClick={saveSecrets} loading={isSaving}>
                {t.saveSecrets}
              </SaveButton>
              <SaveButton onClick={saveConfig} loading={isSaving}>
                {t.saveDefaults}
              </SaveButton>
            </div>
          </Panel>
        )}

        {settingsSection === 'market' && (
          <Panel title={t.marketSettings} icon={<BarChart3 size={17} />}>
            <p className="hint">
              {locale === 'zh'
                ? '用户可以只输入裸代码；每个市场可单独决定是否自动拼接 .region。无论是否拼后缀，market_profile prompt 都会注入到智能体上下文。'
                : 'Users can enter bare symbols; each market controls whether .region is appended. The market_profile prompt is injected either way.'}
            </p>
            <div className="market-profile-grid">
              {metadata.stockMarkets.map((market: any) => {
                const profile = config.marketProfiles?.[market.key] ?? { region: '', appendRegionSuffix: true, weight: '1', marketProfile: '' };
                return (
                  <section key={market.key} className={config.stockMarket === market.key ? 'market-profile-card active' : 'market-profile-card'}>
                    <div className="route-card-head">
                      <div>
                        <strong>{stockMarketLabels[locale][market.key] ?? market.label}</strong>
                        <small>{market.description}</small>
                      </div>
                    </div>
                    <label className="toggle-row compact-toggle">
                      <input
                        type="checkbox"
                        checked={profile.appendRegionSuffix ?? true}
                        onChange={(event) => updateMarketProfile(market.key, { appendRegionSuffix: event.target.checked })}
                      />
                      <span>{t.appendRegionSuffix}</span>
                    </label>
                    <div className="market-profile-fields">
                      <Field label={t.marketRegion}>
                        <input
                          value={profile.region}
                          onChange={(event) => updateMarketProfile(market.key, { region: event.target.value })}
                          placeholder={market.key === 'us' ? 'us' : market.key === 'hk' ? 'hk' : market.key === 'sh' ? 'ss' : 'sz'}
                        />
                      </Field>
                      <Field label={t.marketWeight}>
                        <input
                          value={profile.weight}
                          onChange={(event) => updateMarketProfile(market.key, { weight: event.target.value })}
                          inputMode="decimal"
                        />
                      </Field>
                    </div>
                    <Field label={t.marketPrompt}>
                      <textarea
                        value={profile.marketProfile}
                        onChange={(event) => updateMarketProfile(market.key, { marketProfile: event.target.value })}
                      />
                    </Field>
                  </section>
                );
              })}
            </div>
            <div className="actions-row">
              <SaveButton onClick={saveConfig} loading={isSaving}>
                {t.saveDefaults}
              </SaveButton>
            </div>
          </Panel>
        )}

        {settingsSection === 'data' && (
          <Panel title={t.dataVendors} icon={<Database size={17} />}>
            {metadata.dataVendorCategories.map((category: any) => (
              <Field key={category.key} label={dataVendorLabels[locale][category.key] ?? category.label}>
                <select value={config.dataVendors[category.key] ?? ''} onChange={(event) => updateVendor(category.key, event.target.value)}>
                  {category.options.filter((option: string) => option !== 'custom').map((option: string) => (
                    <option key={option} value={option}>
                      {dataVendorOptionLabel(option, locale)}
                    </option>
                  ))}
                </select>
              </Field>
            ))}
            <div className="section-title">
              <ListOrdered size={16} />
              {t.methodOverrides}
            </div>
            <div className="method-vendor-list">
              {metadata.customDataMethods.map((method: any) => {
                const category = metadata.dataVendorCategories.find((item: any) => item.key === method.category);
                const categoryVendor = config.dataVendors[method.category] ?? '';
                return (
                  <label key={method.method} className="field method-vendor-row">
                    <span>
                      {customMethodLabels[locale][method.method] ?? method.label}
                      <small>{dataVendorLabels[locale][method.category] ?? category?.label ?? method.category}</small>
                    </span>
                    <select value={(config.toolVendors ?? {})[method.method] ?? ''} onChange={(event) => updateToolVendor(method.method, event.target.value)}>
                      <option value="">{t.useCategoryDefault} ({dataVendorOptionLabel(categoryVendor, locale)})</option>
                      {(category?.options ?? []).filter((option: string) => option !== 'custom').map((option: string) => (
                        <option key={option} value={option}>
                          {dataVendorOptionLabel(option, locale)}
                        </option>
                      ))}
                    </select>
                  </label>
                );
              })}
            </div>
          </Panel>
        )}

        {settingsSection === 'data' && (
          <Panel title={t.marketDataVendors} icon={<Database size={17} />}>
            <p className="hint">{t.marketDataHint}</p>
            {dataApiSecretFields.length > 0 && (
              <section className="data-secret-card">
                <div className="section-title">
                  <KeyRound size={16} />
                  {t.dataApiKeys}
                </div>
                <div className="data-secret-grid">
                  {dataApiSecretFields.map((field: string) => (
                    <label key={field} className="secret-row">
                      <span>
                        {field}
                        <small>{secretStatus[field]?.configured ? secretStatus[field]?.masked : t.notConfigured}</small>
                      </span>
                      <input
                        type="password"
                        autoComplete="off"
                        placeholder={secretStatus[field]?.configured ? t.replaceValue : t.pasteKey}
                        value={secretDraft[field] ?? ''}
                        onChange={(event) => setSecretDraft((current: any) => ({ ...current, [field]: event.target.value }))}
                      />
                    </label>
                  ))}
                </div>
                <SaveButton onClick={saveSecrets} loading={isSaving}>
                  {t.saveSecrets}
                </SaveButton>
              </section>
            )}
            <div className="market-data-list">
              {marketDataSections.map((section: any) => {
                const hasOverride = marketGroupHasOverride(section.markets);
                const sectionMarket = section.markets[0];
                return (
                  <details key={section.key} className={hasOverride ? 'market-data-section active' : 'market-data-section'} open={section.markets.includes(config.stockMarket) || hasOverride}>
                    <summary>
                      <span>{section.label}</span>
                      <small>{hasOverride ? t.marketOverrideConfigured : t.inheritDefault}</small>
                    </summary>
                    <div className="market-category-list">
                      {metadata.dataVendorCategories.map((category: any) => {
                        const methods = metadata.customDataMethods.filter((method: any) => method.category === category.key);
                        const inherited = config.dataVendors[category.key] ?? '';
                        const value = sharedMarketValue(section.markets, (market: string) => marketDataOverride(config, market).dataVendors?.[category.key]);
                        const selectedCustom = marketGroupUsesCustomRoute(section.markets, category.key, methods);
                        const settings = marketGroupCustomSettings(section.markets, category.key);
                        return (
                          <section key={`${section.key}-${category.key}`} className={selectedCustom ? 'market-route-card active' : 'market-route-card'}>
                            <div className="market-route-head">
                              <Field label={dataVendorLabels[locale][category.key] ?? category.label}>
                                <select value={value} onChange={(event) => updateMarketGroupVendor(section.markets, category.key, event.target.value)}>
                                  <option value="">{t.inheritDefault} ({dataVendorOptionLabel(inherited, locale)})</option>
                                  {helpers.vendorOptions(category.options, { category: category.key, market: sectionMarket }).map((option: string) => (
                                    <option key={option} value={option}>
                                      {dataVendorOptionLabel(option, locale)}
                                    </option>
                                  ))}
                                </select>
                              </Field>
                              {selectedCustom && (
                                <Field label={t.baseUrl}>
                                  <input
                                    value={settings.baseUrl ?? ''}
                                    onChange={(event) => updateMarketGroupCustomBaseUrl(section.markets, category.key, event.target.value)}
                                    placeholder="https://data.example.com"
                                  />
                                </Field>
                              )}
                            </div>
                            <div className="method-vendor-list market-method-list">
                              {methods.map((method: any) => {
                                const inheritedOverride = sharedMarketValue(section.markets, (market: string) => marketDataOverride(config, market).dataVendors?.[method.category]);
                                const methodInherited = inheritedOverride || config.dataVendors[method.category] || '';
                                const methodValue = sharedMarketValue(section.markets, (market: string) => marketDataOverride(config, market).toolVendors?.[method.method]);
                                return (
                                  <section key={`${section.key}-${method.method}`} className={selectedCustom ? 'market-method-row active' : 'market-method-row'}>
                                    <label className="field method-vendor-row">
                                      <span>
                                        {customMethodLabels[locale][method.method] ?? method.label}
                                        <small>{dataVendorLabels[locale][method.category] ?? category.label}</small>
                                      </span>
                                      <select value={methodValue} onChange={(event) => updateMarketGroupMethodVendor(section.markets, method.method, event.target.value)}>
                                        <option value="">{t.useCategoryDefault} ({dataVendorOptionLabel(methodInherited, locale)})</option>
                                        {helpers.vendorOptions(category.options, { category: method.category, method: method.method, market: sectionMarket }).map((option: string) => (
                                          <option key={option} value={option}>
                                            {dataVendorOptionLabel(option, locale)}
                                          </option>
                                        ))}
                                      </select>
                                    </label>
                                    {selectedCustom && (
                                      <label className="field endpoint-field">
                                        <span>{t.endpointPath}</span>
                                        <input
                                          value={settings.endpoints?.[method.method] ?? method.defaultPath}
                                          onChange={(event) => updateMarketGroupCustomEndpoint(section.markets, category.key, method.method, event.target.value)}
                                          placeholder={method.defaultPath}
                                        />
                                      </label>
                                    )}
                                  </section>
                                );
                              })}
                            </div>
                          </section>
                        );
                      })}
                    </div>
                  </details>
                );
              })}
            </div>
          </Panel>
        )}

        {settingsSection === 'routes' && (
          <Panel title={t.parallelRoutes} icon={<Activity size={17} />}>
            <p className="hint">{t.parallelRoutesHint}</p>
            <div className="route-grid">
              {metadata.llmRouteTargets.map((target: any) => {
                const route = config.llmRoutes?.[target.key] ?? { enabled: false, provider: null, backendUrl: null, modelId: null };
                const routeProvider = route.provider || config.llmProvider;
                const routeProviderMeta = metadata.providers.find((item: any) => item.value === routeProvider);
                const routeModels = routeModelOptions(target.defaultModelRole, routeProvider, route.modelId || modelForRole(config, target.defaultModelRole));
                return (
                  <section key={target.key} className={route.enabled ? 'route-card active' : 'route-card'}>
                    <div className="route-card-head">
                      <div>
                        <strong>{routeLabel(target.label, locale)}</strong>
                        <small>{target.parallelizable ? t.parallelReady : t.sequential}</small>
                      </div>
                      <label className="mini-toggle">
                        <input
                          type="checkbox"
                          checked={route.enabled}
                          onChange={(event) => updateLlmRoute(target.key, { enabled: event.target.checked })}
                        />
                        <span>{t.routeEnabled}</span>
                      </label>
                    </div>
                    <p className="hint">{locale === 'zh' ? routeDescription(target.stage, target.parallelizable) : target.description}</p>
                    <div className="route-fields">
                      <Field label={t.provider}>
                        <select value={route.provider ?? ''} onChange={(event) => updateLlmRoute(target.key, { provider: event.target.value || null })}>
                          <option value="">{t.inheritMainProvider}</option>
                          {metadata.providers.map((item: any) => (
                            <option key={item.value} value={item.value}>
                              {item.label}
                            </option>
                          ))}
                        </select>
                      </Field>
                      <Field label={t.routeBaseUrl}>
                        <input
                          value={route.backendUrl ?? ''}
                          onChange={(event) => updateLlmRoute(target.key, { backendUrl: event.target.value || null })}
                          placeholder={routeProviderMeta?.defaultBaseUrl ?? t.providerDefault}
                        />
                      </Field>
                      <Field label={t.routeModel}>
                        <select value={route.modelId ?? ''} onChange={(event) => updateLlmRoute(target.key, { modelId: event.target.value || null })}>
                          <option value="">{modelForRole(config, target.defaultModelRole)}</option>
                          {routeModels.map((item: any) => (
                            <option key={item.value} value={item.value}>
                              {item.label}
                            </option>
                          ))}
                        </select>
                      </Field>
                      <label className="secret-row route-secret">
                        <span>
                          {target.apiKeyField}
                          <small>{secretStatus[target.apiKeyField]?.configured ? secretStatus[target.apiKeyField]?.masked : t.notConfigured}</small>
                        </span>
                        <input
                          type="password"
                          autoComplete="off"
                          placeholder={secretStatus[target.apiKeyField]?.configured ? t.replaceValue : t.pasteKey}
                          value={secretDraft[target.apiKeyField] ?? ''}
                          onChange={(event) => setSecretDraft((current: any) => ({ ...current, [target.apiKeyField]: event.target.value }))}
                        />
                      </label>
                    </div>
                  </section>
                );
              })}
            </div>
            <div className="actions-row">
              <SaveButton onClick={saveSecrets} loading={isSaving}>
                {t.saveSecrets}
              </SaveButton>
              <SaveButton onClick={saveConfig} loading={isSaving}>
                {t.saveDefaults}
              </SaveButton>
            </div>
          </Panel>
        )}

        {settingsSection === 'backtest' && (
          <Panel title={t.backtestSchedule} icon={<History size={17} />}>
            {backtestConfig ? (
              <div className="backtest-settings">
                <div className="form-grid backtest-settings-grid">
                  <label className="toggle-row compact-toggle">
                    <input
                      type="checkbox"
                      checked={backtestConfig.enabled}
                      onChange={(event) => updateBacktestConfig('enabled', event.target.checked)}
                    />
                    <span>{t.schedulerEnabled}</span>
                  </label>
                  <label className="toggle-row compact-toggle">
                    <input
                      type="checkbox"
                      checked={backtestConfig.checkpointEnabled}
                      onChange={(event) => updateBacktestConfig('checkpointEnabled', event.target.checked)}
                    />
                    <span>{t.checkpointResume}</span>
                  </label>
                  <Field label={t.intervalMinutes}>
                    <input
                      type="number"
                      min={5}
                      max={43200}
                      value={backtestConfig.intervalMinutes}
                      onChange={(event) => updateBacktestConfig('intervalMinutes', clampNumber(event.target.value, 5, 43200))}
                    />
                  </Field>
                  <Field label={t.reviewWindowDays}>
                    <input
                      type="number"
                      min={1}
                      max={3650}
                      value={backtestConfig.reviewWindowDays}
                      onChange={(event) => updateBacktestConfig('reviewWindowDays', clampNumber(event.target.value, 1, 3650))}
                    />
                  </Field>
                  <Field label={t.maxReportsPerCycle}>
                    <input
                      type="number"
                      min={1}
                      max={500}
                      value={backtestConfig.maxReportsPerCycle}
                      onChange={(event) => updateBacktestConfig('maxReportsPerCycle', clampNumber(event.target.value, 1, 500))}
                    />
                  </Field>
                  <Field label={t.priceDataSource}>
                    <select value={backtestConfig.priceDataSource} onChange={(event) => updateBacktestConfig('priceDataSource', event.target.value as any)}>
                      <option value="yfinance">yfinance</option>
                      <option value="custom">custom</option>
                    </select>
                  </Field>
                </div>

                <div className={backtestConfig.priceDataSource === 'custom' ? 'custom-interface active' : 'custom-interface'}>
                  <div className="endpoint-grid">
                    <Field label={t.customBacktestApi}>
                      <input
                        value={backtestConfig.customBaseUrl ?? ''}
                        onChange={(event) => updateBacktestConfig('customBaseUrl', event.target.value || null)}
                        placeholder="https://prices.example.com/api"
                      />
                    </Field>
                    <Field label={t.customBacktestEndpoint}>
                      <input
                        value={backtestConfig.customEndpoint}
                        onChange={(event) => updateBacktestConfig('customEndpoint', event.target.value)}
                        placeholder="/backtest/prices"
                      />
                    </Field>
                  </div>
                  <label className="secret-row provider-secret">
                    <span>
                      BACKTEST_DATA_API_KEY
                      <small>{secretStatus.BACKTEST_DATA_API_KEY?.configured ? secretStatus.BACKTEST_DATA_API_KEY?.masked : t.notConfigured}</small>
                    </span>
                    <input
                      type="password"
                      autoComplete="off"
                      placeholder={secretStatus.BACKTEST_DATA_API_KEY?.configured ? t.replaceValue : t.pasteKey}
                      value={secretDraft.BACKTEST_DATA_API_KEY ?? ''}
                      onChange={(event) => setSecretDraft((current: any) => ({ ...current, BACKTEST_DATA_API_KEY: event.target.value }))}
                    />
                  </label>
                </div>
                <p className="hint">
                  {locale === 'zh'
                    ? 'custom 复盘行情接口应返回 bars/data 数组，每项包含 date、open、high、low、close。已完成的复盘记录不会再次执行；等待数据或失败的记录会从检查点续跑。'
                    : 'A custom review price API should return a bars/data array with date, open, high, low, close. Completed review records are not rerun; waiting-data or failed records resume from checkpoints.'}
                </p>
                <SaveButton onClick={saveBacktestSettings} loading={isSaving} className="full">
                  {t.saveBacktestSettings}
                </SaveButton>
              </div>
            ) : (
              <span className="empty">-</span>
            )}
          </Panel>
        )}
      </section>

      <aside className="settings-side">
        {settingsSection === 'billing' && (
          <Panel title={t.adminBilling} icon={<CreditCard size={17} />}>
            {adminPricing ? (
              <div className="billing-form">
                <div className="form-grid billing-grid">
                  <Field label={t.billingMode}>
                    <select value={adminPricing.billingMode} onChange={(event) => updateAdminPricing('billingMode', event.target.value as any)}>
                      <option value="token">token</option>
                      <option value="per_run">per_run</option>
                      <option value="hybrid">hybrid</option>
                    </select>
                  </Field>
                  <Field label={t.tokenMultiplier}>
                    <input value={adminPricing.tokenMultiplier} onChange={(event) => updateAdminPricing('tokenMultiplier', event.target.value)} inputMode="decimal" />
                  </Field>
                  <Field label={`${t.inputTokens} / 1M`}>
                    <input value={adminPricing.inputTokenPricePer1m} onChange={(event) => updateAdminPricing('inputTokenPricePer1m', event.target.value)} inputMode="decimal" />
                  </Field>
                  <Field label={`${t.outputTokens} / 1M`}>
                    <input value={adminPricing.outputTokenPricePer1m} onChange={(event) => updateAdminPricing('outputTokenPricePer1m', event.target.value)} inputMode="decimal" />
                  </Field>
                  <Field label={t.fixedCharge}>
                    <input value={adminPricing.fixedRunPrice} onChange={(event) => updateAdminPricing('fixedRunPrice', event.target.value)} inputMode="decimal" />
                  </Field>
                  <Field label={t.preauth}>
                    <input value={adminPricing.preauthMultiplier} onChange={(event) => updateAdminPricing('preauthMultiplier', event.target.value)} inputMode="decimal" />
                  </Field>
                </div>
                <div className="depth-price-grid">
                  {(['1', '3', '5'] as const).map((depth) => (
                    <section key={depth} className="depth-price-card">
                      <strong>{researchDepthLabel(Number(depth), depth, locale)}</strong>
                      <Field label={t.tokenMultiplier}>
                        <input value={adminPricing.depthMultipliers[depth] ?? '1'} onChange={(event) => updateDepthPrice('depthMultipliers', depth, event.target.value)} inputMode="decimal" />
                      </Field>
                      <Field label={t.fixedCharge}>
                        <input value={adminPricing.fixedPricesByDepth[depth] ?? '0'} onChange={(event) => updateDepthPrice('fixedPricesByDepth', depth, event.target.value)} inputMode="decimal" />
                      </Field>
                      <Field label={t.inputTokens}>
                        <input value={adminPricing.estimatedInputTokensByDepth[depth] ?? 0} onChange={(event) => updateDepthPrice('estimatedInputTokensByDepth', depth, event.target.value)} inputMode="numeric" />
                      </Field>
                      <Field label={t.outputTokens}>
                        <input value={adminPricing.estimatedOutputTokensByDepth[depth] ?? 0} onChange={(event) => updateDepthPrice('estimatedOutputTokensByDepth', depth, event.target.value)} inputMode="numeric" />
                      </Field>
                    </section>
                  ))}
                </div>
                <Field label={t.modelOverrides}>
                  <textarea
                    value={modelPriceDraft}
                    onChange={(event) => setModelPriceDraft(event.target.value)}
                    spellCheck={false}
                  />
                </Field>
                <SaveButton onClick={saveAdminPricing} loading={isSaving} className="full">
                  {t.saveDefaults}
                </SaveButton>
              </div>
            ) : (
              <span className="empty">-</span>
            )}
          </Panel>
        )}

        {settingsSection === 'users' && (
          <Panel title={t.adminUsers} icon={<Users size={17} />}>
            <div className="new-user-grid">
              <input placeholder={t.username} value={newUserDraft.username} onChange={(event) => setNewUserDraft((current: any) => ({ ...current, username: event.target.value }))} />
              <input placeholder={t.password} type="password" value={newUserDraft.password} onChange={(event) => setNewUserDraft((current: any) => ({ ...current, password: event.target.value }))} />
              <input placeholder={t.initialBalance} value={newUserDraft.initialBalance} onChange={(event) => setNewUserDraft((current: any) => ({ ...current, initialBalance: event.target.value }))} />
              <select value={newUserDraft.role} onChange={(event) => setNewUserDraft((current: any) => ({ ...current, role: event.target.value as 'admin' | 'user' }))}>
                <option value="user">user</option>
                <option value="admin">admin</option>
              </select>
              <button className="secondary" onClick={createAdminManagedUser} disabled={isSaving}>
                <UserPlus size={16} />
                {t.newUser}
              </button>
            </div>
            <div className="user-list">
              {adminUsers.map((user: any) => (
                <section key={user.id} className="user-row">
                  <div>
                    <strong>{user.username}</strong>
                    <small>{user.role} · {formatMoney(user.balance, publicPricing?.currency)} · {t.frozen} {formatMoney(user.frozenBalance, publicPricing?.currency)}</small>
                  </div>
                  <div className="recharge-row">
                    <input placeholder={t.recharge} value={rechargeDraft[user.id] ?? ''} onChange={(event) => setRechargeDraft((current: any) => ({ ...current, [user.id]: event.target.value }))} inputMode="decimal" />
                    <button className="secondary" onClick={() => rechargeUser(user.id)} disabled={isSaving}>
                      <Wallet size={15} />
                      {t.recharge}
                    </button>
                  </div>
                </section>
              ))}
            </div>
          </Panel>
        )}

        {settingsSection !== 'billing' && settingsSection !== 'users' && (
          <Panel title={t.setupRecommendations} icon={<Lightbulb size={17} />}>
            <div className="recommendation-list">
              {setupRecommendations.map((item: string) => (
                <div key={item} className="recommendation-row">
                  <CircleAlert size={15} />
                  <span>{item}</span>
                </div>
              ))}
              {setupRecommendations.length === 0 && <span className="empty">{t.recommendationsOk}</span>}
            </div>
          </Panel>
        )}
      </aside>
    </section>
  );
}
