// Generated by splitting main.tsx into per-view components.
// This file contains the Workspace view's JSX. State/handlers/helpers are
// all typed as `any` so that missing-prop checks don't break the build while
// the rest of the refactor is in flight. The root element is the single
// <section className="workspace-grid workspace-view"> wrapper.

import type { ReactElement } from 'react';

export interface WorkspaceViewProps {
  state: any;
  handlers: any;
  helpers: any;
}

export function WorkspaceView({ state, handlers, helpers }: WorkspaceViewProps): ReactElement {
  const Panel = helpers.Panel;
  const Field = helpers.Field;
  const Metric = helpers.Metric;
  const Selector = helpers.Selector;
  const Chip = helpers.Chip;
  const SaveButton = helpers.SaveButton;
  const Modal = helpers.Modal;
  const formatMoney = helpers.formatMoney;
  const formatDuration = helpers.formatDuration;
  const statusLabel = helpers.statusLabel;
  const today = helpers.today;
  const clampNumber = helpers.clampNumber;
  const researchDepthLabel = helpers.researchDepthLabel;
  const orderTypeLabel = helpers.orderTypeLabel;
  const eventSummary = helpers.eventSummary;
  const stockMarketLabels = helpers.stockMarketLabels ?? state.stockMarketLabels;
  const analystLabels = helpers.analystLabels ?? state.analystLabels;
  const agentLabels = helpers.agentLabels ?? state.agentLabels;
  const eventLabels = helpers.eventLabels ?? state.eventLabels;
  const reportContext = state.reportContext;
  const renderReportReader = helpers.renderReportReader;

  const t = state.t;
  const locale = state.locale;
  const outputLocale = state.outputLocale;
  const activeRun = state.activeRun;
  const config = state.config;
  const metadata = state.metadata;
  const publicPricing = state.publicPricing;
  const currentUser = state.currentUser;
  const batchRuns = state.batchRuns;
  const orders = state.orders;
  const events = state.events;
  const pendingRun = state.pendingRun;
  const tickerList = state.tickerList;
  const historyFilters = state.historyFilters;
  const filteredHistory = state.filteredHistory;
  const selectedHistoryId = state.selectedHistoryId;
  const history = state.history;
  const agentStatus = state.agentStatus;
  const referenceTimeline = state.referenceTimeline;
  const progress = state.progress;
  const runBilling = state.runBilling;
  const effectiveTicker = state.effectiveTicker;
  const timeEstimate = state.timeEstimate;
  const customRouteCount = state.customRouteCount;
  const configuredTickerCount = state.configuredTickerCount;
  const isAdmin = state.isAdmin;
  const isReaderOpen = state.isReaderOpen;
  const isRunning = state.isRunning;
  const isSaving = state.isSaving;
  const customNeedsManualModel = state.customNeedsManualModel;

  return (
    <section className="workspace-grid workspace-view">
      <section className="workspace-overview">
        <div className="overview-card flow-card">
          <div>
            <span>{t.activeWorkflow}</span>
            <strong>{activeRun?.ticker ?? effectiveTicker}</strong>
          </div>
          <div className={`flow-line ${activeRun?.status ?? 'idle'}`}>
            <i />
            <i />
            <i />
            <i />
          </div>
        </div>
        <Metric label={t.configuredAgents} value={`${config.analysts.length} / ${metadata.analysts.length || 4}`} />
        <div className="overview-card price-card">
          <span>{t.pricingPublic}</span>
          <strong>{publicPricing ? `${publicPricing.billingMode} · x${publicPricing.tokenMultiplier}` : '-'}</strong>
          <small>
            {publicPricing
              ? `${t.tokenPrice}: ${formatMoney(publicPricing.inputTokenPricePer1m, publicPricing.currency, 6)}/${formatMoney(publicPricing.outputTokenPricePer1m, publicPricing.currency, 6)} · ${t.fixedCharge}: ${formatMoney(publicPricing.fixedRunPrice, publicPricing.currency)}`
              : '-'}
          </small>
        </div>
        <Metric label={t.dataRouteCount} value={customRouteCount} />
        <Metric label={t.estimateTotal} value={timeEstimate.totalSeconds ? formatDuration(timeEstimate.totalSeconds, locale) : t.estimateWaiting} />
        <Metric label={t.estimateRemaining} value={timeEstimate.remainingSeconds != null ? formatDuration(timeEstimate.remainingSeconds, locale) : '-'} />
        <div className="overview-progress">
          <div>
            <span>{configuredTickerCount > 1 ? `${configuredTickerCount} tickers` : config.outputLanguage}</span>
            <small>{timeEstimate.confidence ? `${timeEstimate.confidence} ${t.estimateConfidence}` : t.estimateWaiting}</small>
          </div>
          <div className="estimate-bar" aria-hidden="true">
            <span style={{ width: `${timeEstimate.percent}%` }} />
          </div>
        </div>
      </section>

      <section className="main-column">
        <Panel title={t.analysisSetup} icon={<helpers.Settings2 size={17} />}>
          <div className="form-grid">
            <label className="field ticker-list-field">
              <span>{t.tickerList}</span>
              <textarea
                value={tickerList}
                onChange={(event) => handlers.changeTickerList(event.target.value)}
                placeholder="SPY, 0700, 600519, 000001"
              />
              <small>{t.tickerListHint}</small>
            </label>
            <Field label={t.stockMarket}>
              <select value={config.stockMarket} onChange={(event) => handlers.changeStockMarket(event.target.value)}>
                {metadata.stockMarkets.map((market: any) => (
                  <option key={market.key} value={market.key}>
                    {stockMarketLabels[locale][market.key] ?? market.label}
                  </option>
                ))}
              </select>
              <small className="field-hint">{t.effectiveTicker}: {effectiveTicker}</small>
            </Field>
            <Field label={t.analysisDate}>
              <input
                type="date"
                max={today()}
                value={config.analysisDate}
                onChange={(event) => handlers.updateConfig('analysisDate', event.target.value)}
              />
            </Field>
            {isAdmin && (
              <Field label={t.provider}>
                <select
                  value={config.llmProvider}
                  onChange={(event) => handlers.changeProvider(event.target.value)}
                >
                  {metadata.providers.map((item: any) => (
                    <option key={item.value} value={item.value}>
                      {item.label}
                    </option>
                  ))}
                </select>
              </Field>
            )}
          </div>

          <div className={isAdmin ? 'tool-row' : 'tool-row single-control'}>
            {isAdmin && (customNeedsManualModel ? (
              <>
                <Field label={t.quickModel}>
                  <input
                    value={config.quickThinkLlm}
                    onChange={(event) => handlers.updateConfig('quickThinkLlm', event.target.value)}
                    placeholder={t.customModelId}
                  />
                </Field>
                <Field label={t.deepModel}>
                  <input
                    value={config.deepThinkLlm}
                    onChange={(event) => handlers.updateConfig('deepThinkLlm', event.target.value)}
                    placeholder={t.customModelId}
                  />
                </Field>
              </>
            ) : (
              <>
                <Selector
                  icon={<helpers.Brain size={16} />}
                  label={t.quickModel}
                  value={config.quickThinkLlm}
                  options={handlers.modelOptionsFor('quick', config.quickThinkLlm)}
                  onChange={(value: any) => handlers.updateConfig('quickThinkLlm', value)}
                />
                <Selector
                  icon={<helpers.Bot size={16} />}
                  label={t.deepModel}
                  value={config.deepThinkLlm}
                  options={handlers.modelOptionsFor('deep', config.deepThinkLlm)}
                  onChange={(value: any) => handlers.updateConfig('deepThinkLlm', value)}
                />
              </>
            ))}
            <Selector
              icon={<helpers.Gauge size={16} />}
              label={t.depth}
              value={String(config.researchDepth)}
              options={metadata.researchDepths.map((item: any) => ({
                label: researchDepthLabel(Number(item.value), item.label, locale),
                value: String(item.value),
              }))}
              onChange={(value: any) => handlers.updateConfig('researchDepth', Number(value) as 1 | 3 | 5)}
            />
          </div>

          <div className="section-title">
            <helpers.BarChart3 size={16} />
            {t.analysts}
          </div>
          <div className="chip-grid">
            {metadata.analysts.map((analyst: any) => (
              <Chip
                key={analyst.value}
                active={config.analysts.includes(analyst.value)}
                onClick={() => handlers.toggleAnalyst(analyst.value)}
              >
                {config.analysts.includes(analyst.value) && <helpers.Check size={14} />}
                {analystLabels[locale][analyst.value] ?? analyst.label}
              </Chip>
            ))}
          </div>

          {isAdmin && (
            <>
              <div className="advanced-grid">
                <Field label={t.openaiReasoning}>
                  <select
                    value={config.openaiReasoningEffort ?? ''}
                    onChange={(event) => handlers.updateConfig('openaiReasoningEffort', event.target.value || null)}
                  >
                    <option value="">{t.providerDefault}</option>
                    <option value="low">{t.low}</option>
                    <option value="medium">{t.medium}</option>
                    <option value="high">{t.high}</option>
                  </select>
                </Field>
                <Field label={t.geminiThinking}>
                  <select
                    value={config.googleThinkingLevel ?? ''}
                    onChange={(event) => handlers.updateConfig('googleThinkingLevel', event.target.value || null)}
                  >
                    <option value="">{t.providerDefault}</option>
                    <option value="minimal">{t.minimal}</option>
                    <option value="high">{t.high}</option>
                  </select>
                </Field>
                <Field label={t.anthropicEffort}>
                  <select
                    value={config.anthropicEffort ?? ''}
                    onChange={(event) => handlers.updateConfig('anthropicEffort', event.target.value || null)}
                  >
                    <option value="">{t.providerDefault}</option>
                    <option value="low">{t.low}</option>
                    <option value="medium">{t.medium}</option>
                    <option value="high">{t.high}</option>
                  </select>
                </Field>
                <Field label={t.parallelRuns}>
                  <input
                    type="number"
                    min={1}
                    max={8}
                    value={config.maxParallelRuns}
                    onChange={(event) => handlers.updateConfig('maxParallelRuns', clampNumber(event.target.value, 1, 8))}
                  />
                </Field>
                <label className="toggle-row">
                  <input
                    type="checkbox"
                    checked={config.checkpointEnabled}
                    onChange={(event) => handlers.updateConfig('checkpointEnabled', event.target.checked)}
                  />
                  <span>{t.checkpointResume}</span>
                </label>
              </div>

              <div className="actions-row">
                <SaveButton onClick={handlers.saveConfig} loading={isSaving}>
                  {t.saveDefaults}
                </SaveButton>
              </div>
            </>
          )}
          {batchRuns.length > 0 && (
            <div className="batch-queue">
              <div className="section-title">
                <helpers.ListOrdered size={16} />
                {t.batchQueue}
              </div>
              <div className="batch-list">
                {batchRuns.map((run: any, index: any) => (
                  <button
                    key={run.id}
                    className={`batch-chip ${run.status}`}
                    onClick={() => handlers.selectLiveRun(run.id)}
                  >
                    {index + 1}. {run.ticker}
                    <small>{statusLabel(run.status, outputLocale)}</small>
                  </button>
                ))}
              </div>
            </div>
          )}
        </Panel>

        <Panel title={t.agentTimeline} icon={<helpers.Activity size={17} />}>
          <div className="agent-grid">
            {Object.entries(agentStatus).map((entry: any) => {
              const [agent, status] = entry;
              return (
              <span key={agent} className={`agent ${status}`}>
                <helpers.BadgeCheck size={15} />
                {agentLabels[outputLocale][agent] ?? agent}
                <small>{statusLabel(status, outputLocale)}</small>
              </span>
              );
            })}
            {referenceTimeline.map((agent: any) => (
              <span key={agent.key} className={`agent reference ${agent.status}`}>
                <helpers.BadgeCheck size={15} />
                {agent.label}
                <small>{statusLabel(agent.status, outputLocale)}</small>
              </span>
            ))}
            {Object.keys(agentStatus).length === 0 && referenceTimeline.length === 0 && <span className="empty">{t.timelineEmpty}</span>}
          </div>
          <div className="metrics-row">
            <Metric label={t.llmCalls} value={progress?.stats?.llm_calls ?? activeRun?.stats?.llm_calls ?? 0} />
            <Metric label={t.toolCalls} value={progress?.stats?.tool_calls ?? activeRun?.stats?.tool_calls ?? 0} />
            <Metric label={t.inputTokens} value={runBilling?.usage.inputTokens ?? progress?.stats?.tokens_in ?? activeRun?.stats?.tokens_in ?? 0} />
            <Metric label={t.outputTokens} value={runBilling?.usage.outputTokens ?? progress?.stats?.tokens_out ?? activeRun?.stats?.tokens_out ?? 0} />
            <Metric label={t.runCost} value={runBilling ? formatMoney(runBilling.actualAmount, runBilling.currency) : '-'} />
            <Metric label={t.preauth} value={runBilling ? formatMoney(runBilling.preauthorizedAmount, runBilling.currency) : '-'} />
            <Metric label={t.balance} value={runBilling?.balanceAfter ? formatMoney(runBilling.balanceAfter, runBilling.currency) : formatMoney(currentUser.balance, publicPricing?.currency)} />
            <Metric label={t.elapsed} value={`${progress?.elapsedSeconds ?? 0}s`} />
          </div>
          <div className="timeline-estimate">
            <div className="estimate-bar" aria-hidden="true">
              <span style={{ width: `${timeEstimate.percent}%` }} />
            </div>
            <span>
              {t.estimateRemaining}: {timeEstimate.remainingSeconds != null ? formatDuration(timeEstimate.remainingSeconds, outputLocale) : '-'}
              {timeEstimate.confidence ? ` · ${timeEstimate.confidence} ${t.estimateConfidence}` : ''}
            </span>
          </div>
        </Panel>

        <Panel
          title={t.reports}
          icon={<helpers.Server size={17} />}
          className="report-panel"
          actions={
            <button
              className="icon-button"
              onClick={() => handlers.setReaderOpen(true)}
              aria-label={t.openReportReader}
              title={t.openReportReader}
            >
              <helpers.Maximize2 size={16} />
            </button>
          }
        >
          {reportContext}
          {renderReportReader()}
        </Panel>
      </section>

      <aside className="right-rail">
        <Panel title={t.reportHistory} icon={<helpers.History size={17} />}>
          <div className="history-filter-bar">
            <label className="filter-input wide">
              <helpers.Search size={14} />
              <input
                value={historyFilters.query}
                onChange={(event) => handlers.setHistoryFilter('query', event.target.value)}
                placeholder={t.reportSearch}
              />
            </label>
            <label className="filter-input">
              <helpers.Filter size={14} />
              <input
                value={historyFilters.ticker}
                onChange={(event) => handlers.setHistoryFilter('ticker', event.target.value)}
                placeholder={t.ticker}
              />
            </label>
            <select
              value={historyFilters.status}
              onChange={(event) => handlers.setHistoryFilter('status', event.target.value)}
            >
              <option value="">{locale === 'zh' ? '状态' : 'Status'}</option>
              {['succeeded', 'failed', 'cancelled', 'running', 'queued'].map((status) => (
                <option key={status} value={status}>
                  {statusLabel(status, locale)}
                </option>
              ))}
            </select>
            <input
              type="date"
              value={historyFilters.date}
              onChange={(event) => handlers.setHistoryFilter('date', event.target.value)}
            />
            <input
              value={historyFilters.provider}
              onChange={(event) => handlers.setHistoryFilter('provider', event.target.value)}
              placeholder={t.provider}
            />
          </div>
          <div className="history-list">
            {filteredHistory.map((item: any) => (
              <button
                key={item.runId}
                className={selectedHistoryId === item.runId ? 'history-row active' : 'history-row'}
                onClick={() => handlers.loadHistoricalReport(item.runId)}
              >
                <span>
                  <strong>{item.ticker}</strong>
                  <small>{item.analysisDate}</small>
                </span>
                <span>
                  <small>{item.provider}</small>
                  <em>{item.decision ?? statusLabel(item.status, locale)}</em>
                </span>
              </button>
            ))}
            {filteredHistory.length === 0 && <span className="empty">{t.historyEmpty}</span>}
          </div>
        </Panel>

        <Panel title={t.orders} icon={<helpers.ReceiptText size={17} />}>
          <div className="order-list">
            {orders.slice(0, 8).map((order: any) => (
              <div key={order.id} className="order-row">
                <span>
                  <strong>{orderTypeLabel(order.type, t)}</strong>
                  <small>{statusLabel(order.status, locale)} · {new Date(order.createdAt).toLocaleString()}</small>
                  {order.errorSummary && (
                    <p className="order-error">{t.errorSummary}: {order.errorSummary}</p>
                  )}
                  {order.status === 'failed_settled' && (
                    <small>
                      {t.failureStage}: {order.errorStage ?? '-'} · {t.chargedOnFailure}: {order.chargedOnFailure ? t.yes : t.no}
                    </small>
                  )}
                </span>
                <span>
                  <em>{formatMoney(order.actualAmount || order.amount || order.frozenAmount, order.currency)}</em>
                  <small>{order.runId ? order.runId.slice(0, 8) : order.externalOrderId ?? '-'}</small>
                  {order.runId && (
                    <button className="text-button compact" onClick={() => handlers.viewOrderRun(order.runId!)}>
                      {t.viewRun}
                    </button>
                  )}
                </span>
              </div>
            ))}
            {orders.length === 0 && <span className="empty">{t.orders}: -</span>}
          </div>
        </Panel>

        <Panel title={t.eventStream} icon={<helpers.TerminalSquare size={17} />}>
          <div className="event-list">
            {[...events].reverse().slice(0, 30).map((event) => (
              <div key={`${event.id}-${event.timestamp}`} className="event-row">
                <span>{eventLabels[outputLocale][event.type] ?? event.type}</span>
                <p>{eventSummary(event, outputLocale)}</p>
              </div>
            ))}
            {events.length === 0 && <span className="empty">{t.eventsEmpty}</span>}
          </div>
        </Panel>
      </aside>
      {isReaderOpen && (
        <Modal
          open
          onClose={() => handlers.setReaderOpen(false)}
          title={t.reports}
          header={
            <div>
              <span>{t.reports}</span>
              <strong>{state.activeReportTitle}</strong>
            </div>
          }
        >
          {reportContext}
          {renderReportReader()}
        </Modal>
      )}
      {pendingRun && (
        <Modal
          open
          onClose={() => handlers.setPendingRun(null)}
          title={t.confirmRunTitle}
          header={
            <div>
              <span>{t.runAnalysis}</span>
              <strong>{t.confirmRunTitle}</strong>
            </div>
          }
        >
          <div className="confirm-modal">
            <p className="hint">{t.confirmRunBody}</p>
            <div className="confirm-metrics">
              <Metric label={t.estimatedFreeze} value={formatMoney(pendingRun.estimate.preauthorizedAmount, pendingRun.estimate.currency)} />
              <Metric label={t.estimatedCharge} value={formatMoney(pendingRun.estimate.estimatedAmount, pendingRun.estimate.currency)} />
              <Metric label={t.runCount} value={pendingRun.estimate.runCount} />
              <Metric label={t.workerCount} value={pendingRun.estimate.maxParallelRuns} />
            </div>
            <div className="confirm-summary">
              <span>{t.provider}: <strong>{pendingRun.estimate.modelProvider}</strong></span>
              <span>{t.quickModel}: <strong>{pendingRun.estimate.quickModel}</strong></span>
              <span>{t.deepModel}: <strong>{pendingRun.estimate.deepModel}</strong></span>
              <span>{t.tickerList}: <strong>{pendingRun.tickers.join(', ')}</strong></span>
            </div>
            <div className="actions-row">
              <button className="secondary" onClick={() => handlers.setPendingRun(null)}>
                {t.cancel}
              </button>
              <button className="primary" onClick={handlers.confirmPendingRun} disabled={isRunning}>
                <helpers.Play size={16} />
                {t.confirmStart}
              </button>
            </div>
          </div>
        </Modal>
      )}
    </section>
  );
}
